version: '3.8'

networks:
  gestion-pub-net:
    driver: bridge

services:
  # ----------------------------
  # CockroachDB: nodo principal
  # ----------------------------
  roach-0:
    image: cockroachdb/cockroach:v23.1.10
    container_name: roach-0
    hostname: roach-0
    networks:
      - gestion-pub-net
    ports:
      - "26257:26257"  # SQL
      - "8090:8080"    # UI (host:container)
    volumes:
      - roach-data-0:/cockroach/cockroach-data
    command: >
      start --insecure
            --advertise-addr=roach-0:26257
            --http-addr=0.0.0.0:8080
            --join=roach-0:26257,roach-1:26257,roach-2:26257
    healthcheck:
      test: ["CMD-SHELL","cockroach node status --insecure --host=roach-0:26257 | grep is_live"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ----------------------------
  # CockroachDB: nodo secundario 1
  # ----------------------------
  roach-1:
    image: cockroachdb/cockroach:v23.1.10
    container_name: roach-1
    hostname: roach-1
    networks:
      - gestion-pub-net
    ports:
      - "26258:26257"
      - "8091:8080"
    volumes:
      - roach-data-1:/cockroach/cockroach-data
    command: >
      start --insecure
            --advertise-addr=roach-1:26257
            --http-addr=0.0.0.0:8080
            --join=roach-0:26257,roach-1:26257,roach-2:26257
    depends_on:
      roach-0:
        condition: service_healthy

  # ----------------------------
  # CockroachDB: nodo secundario 2
  # ----------------------------
  roach-2:
    image: cockroachdb/cockroach:v23.1.10
    container_name: roach-2
    hostname: roach-2
    networks:
      - gestion-pub-net
    ports:
      - "26259:26257"
      - "8092:8080"
    volumes:
      - roach-data-2:/cockroach/cockroach-data
    command: >
      start --insecure
            --advertise-addr=roach-2:26257
            --http-addr=0.0.0.0:8080
            --join=roach-0:26257,roach-1:26257,roach-2:26257
    depends_on:
      roach-0:
        condition: service_healthy

  # ----------------------------
  # Inicializador del clúster
  # ----------------------------
  roach-init:
    image: cockroachdb/cockroach:v23.1.10
    container_name: roach-init
    networks:
      - gestion-pub-net
    command: >
      sh -c "
        sleep 15;
        cockroach init --insecure --host=roach-0:26257 || true
      "
    depends_on:
      roach-0:
        condition: service_healthy
      roach-1:
        condition: service_started
      roach-2:
        condition: service_started

  # ----------------------------
  # Broker RabbitMQ
  # ----------------------------
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    hostname: rabbitmq
    networks:
      - gestion-pub-net
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  roach-data-0:
  roach-data-1:
  roach-data-2:
  rabbitmq-data:
