server:
  port: 8089

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      # CORS global para el front en 63342
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:63342
            allowedHeaders: ["*"]
            allowedMethods: [GET, POST, PUT, DELETE, OPTIONS, PATCH]
            allowCredentials: true

      # Evita cabeceras CORS duplicadas
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
        # (opcional) - RemoveRequestHeader=Cookie

      # Descubrimiento por Eureka
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      # Rutas
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**, /oauth2/**, /login/**
          filters:
            - PreserveHostHeader

        - id: publicaciones-service
          uri: lb://publicaciones-service
          predicates:
            - Path=/api/publications/**   # <-- en inglés, igual que tu controller
          filters:
            - PreserveHostHeader

        - id: catalogo-service-route
          uri: lb://catalogo-service     # ⬅️ minúsculas
          predicates:
            - Path=/api/catalogo,/api/catalogo/**  # ⬅️ acepta ambos prefijos

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
